spring:
    profiles:
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-hjy-dev
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-hjy-test